name: Bug 信息记录
description: 阐述章节 Bug
title: "[章节名称][章节 ID] 文章标题"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        请在这里粘贴您遇到的问题。

  - type: textarea
    attributes:
      label: Bug 信息